### ISSUE TITLE
Enumeration types in case statments

### ISSUE THREAD

**Issue by tenko** [oberon-lang/specification#4]
I found the added enumeration useful and are used to this from Pascal.

I was wondering if the language would benefit from direct support of
enumerations in the case statement?

I see FreePascal at least support this.
(I see also in Oberon+ enumerations are supported in for statements)

Currently i have in my code:
```
case ord(typ) of
        ord(Year) : 
            ...
      | ord(Quarter) :
           ....
```
With an if statement:
```
if typ = Year then
    .....
elsif typ = Quarter then
    .....
...
```
The equivalent if statement would be type safe, but the
case statement would not be type safe.

Just a minor thing, but I thought it could be considered.

**Comment by rochus-keller** [comment]
That looks like an error. Of course CASE statements must support enumerations. I will fix this. 

The current implementation of the parser also doesn't support enumeration variables in CASE statements, but they are supported in IF statements.

**Comment by tenko** [comment]
Excellent. Thanks for the quick response.

**Comment by rochus-keller** [comment]
I fixed the spec, but will release it later. But I also fixed the parser and code generators in IDE version 0.9.30; see commit https://github.com/rochus-keller/Oberon/commit/8af8ee6cfa16ff16683f57a9815c7a380ea42418.

**Comment by rochus-keller** [comment]
Commit is up: c74d414e70470
