### ISSUE TITLE
nop (no operation) operator needed?

### ISSUE THREAD

**Issue by tenko** [oberon-lang/specification#6]
Now when the need for semicolon is removed the following construct
still needs a semicolon:
```
CASE C OF
        0 : ....
        ELSE
           ; // Do nothing
END
```
This could be solved by introducing NOP (operator?)
```
CASE C OF
        0 : ....
        ELSE
          NOP // Do nothing
END
```

**Comment by rochus-keller** [comment]
You can just leave it out, e.g. like

	case t of
	| A: println("A")
	| B..C: println("B")
	| D: println("D")
	else
	end

The same applies e.g. to IF statements.

**Comment by tenko** [comment]
Obvious. 
Though, it takes some time to get used to when scanning code with your eyes.

**Comment by rochus-keller** [comment]
Statement sequences can actually be empty in all Oberon versions since a statement itself is optional.

**Comment by rochus-keller** [comment]
I think we can close this.

Original Oberon forsees to halt the program if there is no ELSE an not all cases are covered in the CASE statement; Oberon+ supports the optional ELSE section but doesn't halt yet; not sure if halting is a good idea; better would be if the compiler would issue an error.
