### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by tenko** [oberon-lang/specification#7]
There is mention of "String concatenation using the + operator".
This is only for constants I presume?
Could not find this mention in the specification.

**Comment by rochus-keller** [comment]
oops, looks like yet another feature I forgot to specify; but it already works, for both constants as well as char arrays; here is an example: https://github.com/rochus-keller/Oberon/blob/master/testcases/ObxTests/Hello.obx

**Comment by tenko** [comment]
A short and concise language specification has the downside that people actually read it!
Excellent. Then it is more powerful than I initially thought.

**Comment by tenko** [comment]
This would then make a hidden NEW allocation operation as the length of the string is not known on compile time.
Would it avoid NEW allocation of a target variable has enough storage?
Should probably be mention in the specification.

**Comment by rochus-keller** [comment]
Yes, it's a dynamic operation. This might be an issue in an embedded application (likely not in all other use cases); maybe dynamic allocations could be avoided by VLAs; or just a compiler opton which limits string adding to constant expressions.

**Comment by rochus-keller** [comment]
To avoid dynamic allocation you could define a const and do the concatenation there.

Specification is updated, commit c74d414e70470
